### PR TITLE
Pre-sort files in file picker; obvious, I hope!

### PR DESCRIPTION
**Pull request by globewalldesk**
This works fine for me in my local install, and makes the file picker usable.

### CODE REVIEW

**Comment by globewalldesk** [comment]
Before and after shots.
Screenshot from 2023-02-07 12-21-07
Screenshot from 2023-02-07 12-17-21

**Comment by globewalldesk** [comment]
I don't often refer to my background to get special favors, but...I am co-founder of Wikipedia, and so I hope you'll accept my pull request soon :-D :-D

**Comment by ilkutkutlar** [comment]
Hello @globewalldesk, great to see that my little project has been useful for someone else, especially the co-founder of Wikipedia! I've merged your pull request, thank you for your contribution :)

**Comment by globewalldesk** [comment]
That was actually my first pull request to another project, ever. I'm not actually a developer, I just picked it up along the way.

**Pull request merged**
